[package]
name = "check-pause-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["contact@dharitri.org"]

[dependencies.check-pause]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.45.1"
path = "../../../../framework/meta"
default-features = false
