[package]
name = "fractional-nfts-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.fractional-nfts]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.46.1"
path = "../../../../framework/meta"
default-features = false
