[package]
name = "erc721-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.erc721]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.43.3"
path = "../../../../../framework/meta"
