[package]
name = "cryptozombies-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.cryptozombies]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.41.3"
path = "../../../../framework/meta"
