[package]
name = "second-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.second-contract]
path = ".."

[dependencies.dharitri-sc]
version = "0.45.2"
path = "../../../../../../framework/base"

[dependencies.dharitri-sc-meta]
version = "0.45.2"
path = "../../../../../../framework/meta"
default-features = false
