[package]
name = "map-repeat-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.map-repeat]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.52.3"
path = "../../../../../framework/meta-lib"
default-features = false
