[package]
name = "payable-features-meta"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[dependencies.payable-features]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.50.3"
path = "../../../../framework/meta"
default-features = false
