[package]
name = "nft-subscription"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "0.45.2"
path = "../../../framework/base"

[dependencies.dharitri-sc-modules]
version = "0.45.2"
path = "../../../contracts/modules"

[dev-dependencies.dharitri-sc-scenario]
version = "0.45.2"
path = "../../../framework/scenario"
